### ISSUE TITLE
Move compaction benchmark to benchmark folder

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#118]
While browsing https://github.com/tonbo-io/tonbo/blob/main/Cargo.toml I discovered `cargo bench`. We should be using this for the compaction benchmark code. Let's:

1. Move the compaction benchmark code to a root-level `perf` folder
2. Add a `[[bench]]` section to `Cargo.toml`

This way we can use `cargo bench` to run our benchmarks.

**Comment by wasup-yash** [comment]
I would like to take work on it :)

**Comment by criccomini** [comment]
@wasup-yash go for it! Note that #125 is adding some docs, so depending on who merges first, you might have to do a smidge of rebasing.

**Comment by wasup-yash** [comment]
> @wasup-yash go for it! Note that #125 is adding some docs, so depending on who merges first, you might have to do a smidge of rebasing.

should we move bench folder to the same level as src ?, as defined in the book https://doc.rust-lang.org/cargo/guide/project-layout.html

**Comment by rodesai** [comment]
I did take a look at cargo bench for this initially. I'm not sure this particular "benchmark" (maybe we should change the name) is appropriate as a [cargo benchmark](https://doc.rust-lang.org/unstable-book/library-features/test.html). My understanding of `cargo bench` is that it's meant to benchmark some small, short-running (useconds or milliseconds) unit of code which also has minimal setup overhead - kind of like a JMH microbenchmark if you're familiar with the Java ecosystem, acting as kind of a "perf unit test". It'll try to run that over lots of iterations and compute an average runtime.

My intent with compaction_execute_bench was to have a tool that we could run to measure the actual speed at which we can compact large volumes of SSTs/SRs against a real object store, which seems beyond the scope of what cargo bench is intended for. Some problems I foresee:
- there's a long setup phase (that we want to be able to reuse across multiple executions of the benchmark so we can optimize-test-optimize-test-...), so we'd want to make that optional and executable from some other tool.
- the benchmark runs for a long time (multiple minutes). The examples in the cargo bench docs are for stuff that runs in nano and micro seconds. The benchmark framework tries to be smart about calculating how many iterations to run based on how long the tests take, variance, etc - I'm not sure how it will handle long running tests.

Also, somewhat tangentially, the core of the benchmark code lives in lib/ because it uses internal apis. I'd prefer that we not make apis public just to expose them for benchmarks (though it seems weird we'd have to given that cargo bench seems to be a microbenchmarking framework - so I may be misunderstanding something). So even if we were to use cargo bench I'd prefer that we keep the main code for the benchmark alongside the lib.

**Comment by criccomini** [comment]
Ah, gotcha! My bad, I misunderstood the benchmark feature for Cargo.

It does bug me that we have bench code inside the main library, but I take your point on the internal API usage. I wonder if, longer term, it makes more sense to replace the compaction benchmark with one that uses public APIs. We want to eventually support compaction as a separate process; perhaps when we do that, we can run expose the appropriate APIs to allow benchmarking *just* the compaction portion.

In the meantime, I'm going to close this. I'm going to open a separate ticket to add benchmarks (eventually) for SlateDB as Cargo's `bench` intends.

@wasup-yash I apologize for steering you in the wrong direction. This one was my bad.
