### ISSUE TITLE
Add an option to disable the bloom filter on the last sorted run

### ISSUE THREAD

**Issue by criccomini** [slatedb/slatedb#167]
Users should be able to disable the bloom filter on the last sorted run. This is good for use cases with a high positive read rate. This will let you reduce filter memory usage, or use more bits on your filters to help cull the search space.

/cc @rodesai for additional detail

**Comment by criccomini** [comment]
From Rohan:

> an option to disable the bloom filter on the last sorted run (good for use cases with a high positive read rate). This will let you reduce filter memory usage, or use more bits on your filters to help cull the search space.

SlateDB's compactor compacts SSTs down periodically. Each compaction produces sorted runs (SRs), which are basically collections of SSTs that are range partitioned. The "last" sorted run" is always the largest. ("last" = "oldest" = "most of the key-values")

The idea with this issue is to be able to disable the bloom filter just for the last sorted run via a CompactorOptions setting.

As Rohan says, this would allow users to save memory/storage space in cases where they know that get()'s are likely to be a "hit" (i.e. to be contained in the database).

**Comment by dyedgreen** [comment]
Interested in taking a look at this! 👀

**Comment by criccomini** [comment]
Assigned! :)

**Comment by agavra** [comment]
Would it make sense to have this be a little more generic than just disabling BF for the last level and instead allow you to configure a function that computes BF size for each Level `L`? Here's a summary of the Monkey strategy (quoted from Dostevesky)

> While mainstream designs along the top curve in Figure 1 set the same false positive rate to Bloom filters across all levels of LSM-tree, Monkey, the current state of the art, sets exponentially lower false positive rates to Bloom filters at smaller levels [22]. This is shown to minimize the sum of false positive rates across all filters and to thereby minimize I/O for point lookups. At the same time, this means that access to smaller levels is exponentially less probable. Therefore, most point lookup I/Os target the largest level.

This is basically the opposite of the suggested ticket for certain situations where you want larger BFs as you go deeper into the levels.

**Comment by agavra** [comment]
Ah looks like Rohan has already commented about that in #163 -- we may want to close this as duplicate?

**Comment by criccomini** [comment]
@agavra @dyedgreen Thought about this a bit. I'm going to close this issue in favor of 163.

Initially, I thought maybe we could tweak this issue to impe implement an API that will allow us to evolve the filter bits per-SST, and implement the configured bits/key for all SSTs except the last SR's SSTs. But I don't want to add _more_ config that we then end up having to delete once we implement 163. I think this right solution 163 (and thus, this ticket) is to build something adaptive/algorithmic.

Therefore, I'm going to close this. @dyedgreen I'm really sorry for the burned time.

**Comment by rodesai** [comment]
Making the filter bit assignment fully adaptive feels like a big effort. In general, implementing the optimization proposed by Monkey is tricky. They propose how to compute a FPR distribution on a stable tree where you know the number of levels with filters and their size (in number of keys). But it's not at all clear to me how to do this on an actual system where you don't know this information up front and have to figure it out as it grows. We'll probably need some kind of hints from the user, but I'm not sure how exactly this would work. It needs a bunch more thought.

That said, this particular optimization (disabling filters), is somewhat orthogonal - we need to know whether or not the db is doing lots of negative lookups and enable/disable filters on the last level accordingly. I think this is a different optimization from tuning the number of bits per key on the higher levels based on their size. So I think it makes sense to keep this ticket open, and perhaps extend it to decide whether or not to enable/disable filters based on the observed proportion of negative lookups rather than adding an on/off config. Alternatively, we can make the config the % of negative lookups for which to disable filters. Initially, we can just enable the filters when the property is set to 0 and disable them otherwise, and then add the improvement to measure the negative lookup rate in another patch.

Finally, this is a somewhat complex change so I think we should try to test whether it's actually beneficial. The test should build up a sizeable db and assess:
- how much cache we need to keep filters in memory with filters enabled/disabled on the last level
- what the difference in perf is with an in-memory + on-disk cache and postive lookups with filters enabled/disabled on the last level. Basically, if we enable filters on the last level but they are still cached on disk, how much does that hurt performance.

> This is basically the opposite of the suggested ticket for certain situations where you want larger BFs as you go deeper into the levels.

I didn't follow this. The excerpt you quoted is just describing what happens when you have smaller filters at the higher levels.  Overall you have less I/O, and it's concentrated on the deeper levels.

@agavra @criccomini

**Comment by agavra** [comment]
> I didn't follow this. The excerpt you quoted is just describing what happens when you have smaller filters at the higher levels. Overall you have less I/O, and it's concentrated on the deeper levels.

It seems I had actually misread my initial quotation of that paper (too many double negatives). I thought it was saying you want to set a much higher rate of false positives on higher levels in the tree and the opposite for lower levels. But after re-reading it I see that it suggests the opposite. My thought process is that it's more expensive to have a false positive on a larger SST than it is on a smaller one, so you should optimize for larger filters at lower levels. Clearly I had the opposite understanding.

**Comment by rodesai** [comment]
> My thought process is that it's more expensive to have a false positive on a larger SST than it is on a smaller one, so you should optimize for larger filters at lower levels.

I agree with you here. I think this is one of the things that they don't really address in the paper, and something that makes me skeptical about the optimization in general. I think it is likely to be more expensive to get a false positive on a deeper SST:
- It's larger, so you then have to read a larger index to get to the block. This can be somewhat mitigated with a multi-level index, though you then have to pay for reading multiple levels of index.
- The shallower levels are much more likely to be present in cache, so they should be much cheaper to read.

All the more reason to hold off on the general optimization until we hit a use case that can benefit from it. And how we actually implement it and let the user configure it needs more thought.

**Comment by marvin-j97** [comment]
> In general, implementing the optimization proposed by Monkey is tricky. They propose how to compute a FPR distribution on a stable tree where you know the number of levels with filters and their size (in number of keys). But it's not at all clear to me how to do this on an actual system where you don't know this information up front and have to figure it out as it grows.

I have found this to be [the case as well](https://github.com/fjall-rs/lsm-tree/blob/main/src/compaction/worker.rs#L192-L202), you need heuristics or user configuration to calculate the size, so implementing it is almost impossible without making assumptions...

*However*, L0 segments (and maybe L1) are so small and short-lived that aggressively hard coding a low FPR makes sense because it is so cheap - we want to avoid disk superfluous I/O in L0 at all costs.

Compare this 10-bit per key filter for 1M items. It costs ~1.2 MiB and has a ~0.8% FPR.
![image](https://github.com/user-attachments/assets/4e314392-2fe8-4998-92dd-23f5006b534d)

Now compare this MONKEY-esque filter, it costs just 1.7 MiB, but has 8x better FPR:
![image](https://github.com/user-attachments/assets/5cebc38d-3e65-4ea5-9ad7-7e5d95a55049)

Now make it more crazy, this one just costs 2.9 MiB and has a 800x better FPR: 
![image](https://github.com/user-attachments/assets/4370d10d-e989-445f-b755-2ec1dc8b312c)

**Comment by criccomini** [comment]
Can reopen if we find we need it.
