### ISSUE TITLE
integrate with nyrkio for performance regression detection

### ISSUE THREAD

**Issue by flaneur2020** [slatedb/slatedb#408]
came across this service while surfing the internet:

https://nyrkio.com/

it seems being used by tigerbeetle 👀

**Comment by criccomini** [comment]
What are the advantages over what we have now? I took a brief look and it looks a lot like what we have with our GitHub benchmark action.

**Comment by flaneur2020** [comment]
yes indeed 🙈, it seems features performance regression detection, but we have made it in pr comment, so i guess the advantage is negligible.

let me close this issue, if anybody knows more about it, please comment below

**Comment by criccomini** [comment]
SGTM. I'm kinda curious. I hadn't heard of it. I might reach out to @jorangreef to ask how they arrived at it.

**Comment by henrikingo** [comment]
Hi
Just leaving a short note for educational purposes, hope it is ok. (I can delete this if you consider it spammy?)

 I'm one of the developers at Nyrkiö but more importantly was a member of the Mongodb perf team 10 years ago when we implemented the change detection algorithm that my boss had found in an article. In short, most practitioners nowadays will check benchmark results with some simple heuristic like compare today's result to yesterday's. A slightly better version of this is to compare against an average of recent results. This was at least at MongoDB a terrible experience and didn't scale, so the number of automated performance  tests remained small because we couldn't deal with all the false positive alerts. (Depending how you count,we had more than 90% false positive rate.)

The algorithm used by Nyrkiö otoh looks at the entire history of performance results and then tries to find statistically significant, persisting changes. So the question it asks is completely different: "Is today's test result worse than yesterday" vs "in my entire history of results, was there a point in time that the trendline / mean changed permanently"? So by looking  at more data it is able to produce more accurate answers.

Otoh at Nyrkiö we currently don't do anything for running the benchmark. We just help you deal with the results.
